division and subtraction have been implemented and tested. This shoul…
lancefisher/cellular pull request #3
Opened 2017-06-12 18:59 UTC by William-Charles

…d have been multiple commits.

2017-06-15 18:55 UTC, lancefisher requested changes
Hi Will, thanks for the PR! This looks good. Just need to add a test and use single quotes.

2017-06-15 18:55 UTC, lancefisher commented on src/CellularParser.test.js
> +  "2 / 1",
This is good. I'd like to add at least one test that verifies precedence with `/`.

2017-06-15 18:55 UTC, lancefisher commented on src/Cell.js
> +    if (this.text[0] !== "=") return true;
I've standardized on single quotes. Can you leave them, please?

2017-06-18 04:04 UTC, William-Charles commented
Made the changes requested and I am getting all green tests.

2017-06-18 04:06 UTC, William-Charles commented
I made the changed the double quotes back to single and added a division
precedence test to the interpreter.test file. The test is dividing before
addition.

On Thu, Jun 15, 2017 at 12:55 PM, Lance Fisher <notifications@github.com>
wrote:

> *@lancefisher* requested changes on this pull request.
>
> Hi Will, thanks for the PR! This looks good. Just need to add a test and
> use single quotes.
> ------------------------------
>
> In src/CellularParser.test.js
> <https://github.com/lancefisher/cellularjs/pull/3#discussion_r122283589>:
>
> > +
> +shouldParseAs(
> +  "1 * 2 - 3",
> +  new OperatorExpression(
> +    new OperatorExpression(
> +      new NumberExpression("1"),
> +      TokenTypes.TIMES,
> +      new NumberExpression("2")
> +    ),
> +    TokenTypes.MINUS,
> +    new NumberExpression("3")
> +  )
> +);
> +
> +shouldParseAs(
> +  "2 / 1",
>
> This is good. I'd like to add at least one test that verifies precedence
> with /.
> ------------------------------
>
> In src/Cell.js
> <https://github.com/lancefisher/cellularjs/pull/3#discussion_r122283782>:
>
> > @@ -25,8 +25,8 @@ export default class Cell {
>    }
>
>    isLiteral() {
> -    if (typeof this.text === 'number') return true;
> -    if (this.text[0] !== '=') return true;
> +    if (typeof this.text === "number") return true;
> +    if (this.text[0] !== "=") return true;
>
> I've standardized on single quotes. Can you leave them, please?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/lancefisher/cellularjs/pull/3#pullrequestreview-44386807>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AWcP7pthu_1OUGjKRipXz0XWol--yEdRks5sEX4pgaJpZM4N3i7n>
> .
>

2017-06-19 06:20 UTC, lancefisher requested changes

2017-06-19 06:20 UTC, lancefisher commented on src/Cell.sublime-workspace
> +{
Please exclude this file. You can add `src/Cell.sublime-workspace` to `.gitignore`.

2017-06-19 06:20 UTC, lancefisher commented on src/tokenizer.test.js
> +  new Token(TokenTypes.EOF)
Looks like a bunch of these changes are unrelated. I think your editor removed the trailing commas here. I want to leave them to follow the [airbnb styleguide](https://github.com/airbnb/javascript).

2017-06-19 06:20 UTC, lancefisher commented on src/tokenizer.test.js
> +  new Token(TokenTypes.EOF)
Please run `yarn lint` and fix linting errors. Trailing commas are a lint rule.

2017-06-19 06:20 UTC, lancefisher commented on src/tokenizer.js
> +      let value = "";
This should be `''` (single quotes).

2017-06-19 06:20 UTC, lancefisher commented on src/tokenizer.js
> +          throw new TypeError('Invalid number format x.x.');
No need to change this to two lines. Prefer to keep simple checks on one line.

2017-06-19 06:20 UTC, lancefisher commented on src/tokenizer.js
> +export { tokenize, Token, TokenTypes };
Not that big of deal in this case, but avoid making style changes like this that aren't related to the addition.

2017-06-20 14:24 UTC, William-Charles commented
Hey Lance,
Thank you for being patient with me and allowing me to workout me editor
auto changes.
Will

On Mon, Jun 19, 2017 at 12:20 AM, Lance Fisher <notifications@github.com>
wrote:

> *@lancefisher* requested changes on this pull request.
> ------------------------------
>
> In src/Cell.sublime-workspace
> <https://github.com/lancefisher/cellularjs/pull/3#discussion_r122626333>:
>
> > @@ -0,0 +1,574 @@
> +{
>
> Please exclude this file. You can add src/Cell.sublime-workspace to
> .gitignore.
> ------------------------------
>
> In src/tokenizer.test.js
> <https://github.com/lancefisher/cellularjs/pull/3#discussion_r122626562>:
>
> > @@ -33,18 +29,18 @@ tokensShouldBe('SUM(A1:B2)', [
>    new Token(TokenTypes.COLON, ':'),
>    new Token(TokenTypes.NAME, 'B2'),
>    new Token(TokenTypes.RPAREN, ')'),
> -  new Token(TokenTypes.EOF),
> +  new Token(TokenTypes.EOF)
>
> Looks like a bunch of these changes are unrelated. I think your editor
> removed the trailing commas here. I want to leave them to follow the airbnb
> styleguide <https://github.com/airbnb/javascript>.
> ------------------------------
>
> In src/tokenizer.test.js
> <https://github.com/lancefisher/cellularjs/pull/3#discussion_r122626629>:
>
> >  ]);
>
>  tokensShouldBe('1 + 2', [
>    new Token(TokenTypes.NUMBER, '1'),
>    new Token(TokenTypes.PLUS, '+'),
>    new Token(TokenTypes.NUMBER, '2'),
> -  new Token(TokenTypes.EOF),
> +  new Token(TokenTypes.EOF)
> +]);
> +
> +tokensShouldBe('2 - 1', [
> +  new Token(TokenTypes.NUMBER, '2'),
> +  new Token(TokenTypes.MINUS, '-'),
> +  new Token(TokenTypes.NUMBER, '1'),
> +  new Token(TokenTypes.EOF)
>
> Please run yarn lint and fix linting errors. Trailing commas are a lint
> rule.
> ------------------------------
>
> In src/tokenizer.js
> <https://github.com/lancefisher/cellularjs/pull/3#discussion_r122626821>:
>
> >
>      if (char === '"') {
> -      let value = '';
> +      let value = "";
>
> This should be '' (single quotes).
> ------------------------------
>
> In src/tokenizer.js
> <https://github.com/lancefisher/cellularjs/pull/3#discussion_r122626965>:
>
> >          const isDot = char === '.';
> -        if (foundDot && isDot) throw new TypeError('Invalid number format x.x.');
> +        if (foundDot && isDot)
> +          throw new TypeError('Invalid number format x.x.');
>
> No need to change this to two lines. Prefer to keep simple checks on one
> line.
> ------------------------------
>
> In src/tokenizer.js
> <https://github.com/lancefisher/cellularjs/pull/3#discussion_r122627460>:
>
> >      );
>    }
>
>    tokens.push(new Token(TokenTypes.EOF));
>    return tokens;
>  }
>
> -export {
> -    tokenize,
> -    Token,
> -    TokenTypes,
> -};
> +export { tokenize, Token, TokenTypes };
>
> Not that big of deal in this case, but avoid making style changes like
> this that aren't related to the addition.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/lancefisher/cellularjs/pull/3#pullrequestreview-44756809>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AWcP7gmbBOOdpGUU8JDM1ifovc_z-Ljmks5sFhM4gaJpZM4N3i7n>
> .
>

2017-06-20 17:50 UTC, lancefisher commented
No worries! It would be nice to clean up the PR title and description too. Explain what you're adding here, etc. It serves as a historical record for the project. Thanks for the PR!

2017-06-20 17:55 UTC, lancefisher commented
Tests and linting passed. Looks good.

2017-06-20 17:55 UTC, lancefisher approved these changes

2017-06-20 17:58 UTC, merged